# Generated by Django 5.0 on 2025-02-25 09:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('location_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('tilte_name', models.CharField(max_length=30)),
                ('has_passport', models.BooleanField(default=True)),
                ('salary', models.IntegerField(default=None)),
                ('brith_date', models.DateField(default=None)),
                ('hire_date', models.DateField(default=None)),
                ('notes', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('AUS', 'Australia'), ('UA', 'Austria'), ('SP', 'Spain'), ('CAN', 'Canada'), ('GER', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('JPN', 'Japan'), ('CHN', 'China'), ('RUS', 'Russia'), ('CHL', 'Chile'), ('SWE', 'Sweden'), ('NOR', 'Norway'), ('FIN', 'Finland'), ('DEN', 'Denmark'), ('BEL', 'Belgium'), ('CHE', 'Switzerland'), ('NZ', 'New Zealand'), ('SGP', 'Singapore'), ('KOR', 'South Korea'), ('SA', 'South Africa'), ('ARG', 'Argentina'), ('COL', 'Colombia'), ('PHL', 'Philippines'), ('THA', 'Thailand'), ('NET', 'Netherland'), ('IRL', 'Ireland'), ('AUT', 'Austria'), ('HUN', 'Hungary'), ('CZE', 'Czech Republic'), ('POL', 'Poland'), ('POR', 'Portugal'), ('GRC', 'Greece'), ('TUR', 'Turkey'), ('UAE', 'United Arab Emirates'), ('EGY', 'Egypt'), ('KEN', 'Kenya'), ('NGA', 'Nigeria'), ('VNM', 'Vietnam'), ('MYS', 'Malaysia'), ('IDN', 'Indonesia'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('BGR', 'Bulgaria'), ('ROU', 'Romania'), ('LVA', 'Latvia'), ('LTU', 'Lithuania'), ('EST', 'Estonia'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('CYP', 'Cyprus'), ('LUX', 'Luxembourg'), ('MLT', 'Malta'), ('AND', 'Andorra'), ('MON', 'Monaco'), ('SMR', 'San Marino'), ('VAT', 'Vatican City'), ('ISL', 'Iceland'), ('KAZ', 'Kazakhstan'), ('AZE', 'Azerbaijan'), ('GEO', 'Georgia'), ('ARM', 'Armenia'), ('KIR', 'Kiribati'), ('TUV', 'Tuvalu'), ('WSM', 'Samoa'), ('FJI', 'Fiji'), ('PNG', 'Papua New Guinea'), ('TLS', 'Timor-Leste')], default=None, max_length=35)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djangobasicapp.department')),
                ('destination_country', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='djangobasicapp.country')),
            ],
        ),
    ]
