# Generated by Django 5.0 on 2025-02-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisrt_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('tilte_name', models.CharField(max_length=30)),
                ('has_passport', models.BooleanField(default=True)),
                ('salary', models.IntegerField(default=None)),
                ('brith_date', models.DateField(default=None)),
                ('hire_date', models.DateField(default=None)),
                ('notes', models.CharField(max_length=200)),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('AUS', 'Australia'), ('UA', 'Austria'), ('SP', 'Spain')], default=None, max_length=35)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
