# Generated by Django 5.0 on 2025-02-25 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobasicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='User Name')),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Confirm Password')),
                ('gender', models.CharField(choices=[('FE', 'Female'), ('MA', 'Male')], default=None, max_length=10, verbose_name='Gender')),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('AUS', 'Australia'), ('UA', 'Austria'), ('SP', 'Spain'), ('CAN', 'Canada'), ('GER', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('JPN', 'Japan'), ('CHN', 'China'), ('RUS', 'Russia'), ('CHL', 'Chile'), ('SWE', 'Sweden'), ('NOR', 'Norway'), ('FIN', 'Finland'), ('DEN', 'Denmark'), ('BEL', 'Belgium'), ('CHE', 'Switzerland'), ('NZ', 'New Zealand'), ('SGP', 'Singapore'), ('KOR', 'South Korea'), ('SA', 'South Africa'), ('ARG', 'Argentina'), ('COL', 'Colombia'), ('PHL', 'Philippines'), ('THA', 'Thailand'), ('NET', 'Netherland'), ('IRL', 'Ireland'), ('AUT', 'Austria'), ('HUN', 'Hungary'), ('CZE', 'Czech Republic'), ('POL', 'Poland'), ('POR', 'Portugal'), ('GRC', 'Greece'), ('TUR', 'Turkey'), ('UAE', 'United Arab Emirates'), ('EGY', 'Egypt'), ('KEN', 'Kenya'), ('NGA', 'Nigeria'), ('VNM', 'Vietnam'), ('MYS', 'Malaysia'), ('IDN', 'Indonesia'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('BGR', 'Bulgaria'), ('ROU', 'Romania'), ('LVA', 'Latvia'), ('LTU', 'Lithuania'), ('EST', 'Estonia'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('CYP', 'Cyprus'), ('LUX', 'Luxembourg'), ('MLT', 'Malta'), ('AND', 'Andorra'), ('MON', 'Monaco'), ('SMR', 'San Marino'), ('VAT', 'Vatican City'), ('ISL', 'Iceland'), ('KAZ', 'Kazakhstan'), ('AZE', 'Azerbaijan'), ('GEO', 'Georgia'), ('ARM', 'Armenia'), ('KIR', 'Kiribati'), ('TUV', 'Tuvalu'), ('WSM', 'Samoa'), ('FJI', 'Fiji'), ('PNG', 'Papua New Guinea'), ('TLS', 'Timor-Leste')], default=None, max_length=35, verbose_name='Country')),
                ('brith_date', models.DateField(default=None, verbose_name='Date of Birth')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='Email')),
            ],
        ),
    ]
