# Generated by Django 5.0 on 2025-02-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobasicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
