# Generated by Django 5.0 on 2025-02-26 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysample.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysample.countries')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='querysample.sate')),
            ],
        ),
    ]
