# Generated by Django 5.0 on 2025-02-27 19:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country', models.CharField(choices=[('IND', 'India'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('AUS', 'Australia'), ('UA', 'Austria'), ('SP', 'Spain'), ('CAN', 'Canada'), ('GER', 'Germany'), ('FRA', 'France'), ('ITA', 'Italy'), ('BRA', 'Brazil'), ('MEX', 'Mexico'), ('JPN', 'Japan'), ('CHN', 'China'), ('RUS', 'Russia'), ('CHL', 'Chile'), ('SWE', 'Sweden'), ('NOR', 'Norway'), ('FIN', 'Finland'), ('DEN', 'Denmark'), ('BEL', 'Belgium'), ('CHE', 'Switzerland'), ('NZ', 'New Zealand'), ('SGP', 'Singapore'), ('KOR', 'South Korea'), ('SA', 'South Africa'), ('ARG', 'Argentina'), ('COL', 'Colombia'), ('PHL', 'Philippines'), ('THA', 'Thailand'), ('NET', 'Netherland'), ('IRL', 'Ireland'), ('AUT', 'Austria'), ('HUN', 'Hungary'), ('CZE', 'Czech Republic'), ('POL', 'Poland'), ('POR', 'Portugal'), ('GRC', 'Greece'), ('TUR', 'Turkey'), ('UAE', 'United Arab Emirates'), ('EGY', 'Egypt'), ('KEN', 'Kenya'), ('NGA', 'Nigeria'), ('VNM', 'Vietnam'), ('MYS', 'Malaysia'), ('IDN', 'Indonesia'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('BGR', 'Bulgaria'), ('ROU', 'Romania'), ('LVA', 'Latvia'), ('LTU', 'Lithuania'), ('EST', 'Estonia'), ('SVK', 'Slovakia'), ('SVN', 'Slovenia'), ('CYP', 'Cyprus'), ('LUX', 'Luxembourg'), ('MLT', 'Malta'), ('AND', 'Andorra'), ('MON', 'Monaco'), ('SMR', 'San Marino'), ('VAT', 'Vatican City'), ('ISL', 'Iceland'), ('KAZ', 'Kazakhstan'), ('AZE', 'Azerbaijan'), ('GEO', 'Georgia'), ('ARM', 'Armenia'), ('KIR', 'Kiribati'), ('TUV', 'Tuvalu'), ('WSM', 'Samoa'), ('FJI', 'Fiji'), ('PNG', 'Papua New Guinea'), ('TLS', 'Timor-Leste')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
